name: YouTube fetch hourly

on:
  schedule:
    - cron: "0 * * * *"   # JSTでも毎時00分に起動（GitHubはUTCなので±0でOK）
  workflow_dispatch:

permissions:
  contents: write   # 自動コミットに必要

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # 念のため完全履歴（なくても可）

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          python main.py

      - name: Commit & push updated Excel
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update youtube_videos.xlsx (auto)"
          file_pattern: youtube_videos.xlsx
