# .github/workflows/main.yml

name: Fetch and Update YouTube Videos

on:
  workflow_dispatch:
  schedule:
    # UTC時間で1時間ごとに実行 (例: 毎日0時,1時,2時...に実行)
    # 日本時間(JST)では、毎日9時,10時,11時...に相当
    - cron: '0 */1 * * *'

jobs:
  update-videos:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests openpyxl
          
      - name: Run Python script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          python main.py
          
      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add youtube_videos.xlsx
          git commit -m "chore: Add new YouTube videos [skip ci]" || echo "No changes to commit"
          git push
